---
- hosts: localhost
  connection: local	# not the default (ssh) as it will be parsed localy
  become: true

  vars:
    ansible_user: mike  # Define the local user as a variable

  tasks:
  - name: install packages                           # The name that it will be appeared on the playbook when it is finished
    tags: always
    package:                                         # ansible has many modules. Package is one of them
      name: 
        - htop 
        - tmux
        - zsh
        - git

  - name: Install Visual Studio Code
    command: snap install --classic code
    become: yes

  - name: Install Slack
    command: snap install slack
    become: yes

  - name: Install Docker Engine
    command: snap install slack
    become: yes

  - name: copy .bashrc file
    tags: always
    copy:
      src: files/bashrc                                             # needs to create a files dir, access it and "cp ~/.bashrc bashrc"
      dest: /home/{{ ansible_user }}/.bashrc                        # copy the bashrc file that i will download from git, on its normal path as a hidden file
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: copy .zshrc file
    tags: always
    copy:
      src: files/bashrc
      dest: /home/{{ ansible_user }}/.zshrc	
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: add ansible user
    tags: user
    user:
      name: ansible
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible                     # i will copy the file that i will fetch on the /etc/sudoers.d group
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible
      minute: "*/30"                                                                               # run every 30 minutes
      job: ansible-pull -o -U https://github.com/micksar/Ansible_new_pc_configuration.git          # the repository url. -o argument, says ansible to run only when there are changes. It checks every 10 mins






