---
- hosts: localhost
  connection: local	# not the default (ssh) as it will be oarsed localy
  become: true

  tasks:
  - name: install packages
    package: 
      name: 
        - htop 
        - tmux
